DUMMY_CONSTANT_1 = 'xyz'
DUMMY_CONSTANT_2 = 'zyx'
DUMMY_CONSTANTS = [DUMMY_CONSTANT_1, DUMMY_CONSTANT_2]
DUMMY_CONSTANT_TEMPLATE = 'abc'
VARIABLE_PREFIX = 'X'
DUMMY_VARIABLE_1 = 'XYZ'
DUMMY_VARIABLE_2 = 'ZYX'
